# Generated by Django 4.2.6 on 2023-10-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('local', models.CharField(max_length=255)),
                ('dress_code', models.TextField()),
            ],
        ),
    ]
